# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: ironhacks

day_night: false
font: ''
font_size: M

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: ''
twitter: ''

email: opendigital@purdue.edu
# phone: 888 888 88 88
# address:
#   street: 450 Serra Mall
#   city: Stanford
#   region: CA
#   postcode: '94305'
#   country: United States
#   country_code: US
# coordinates:
#   latitude: '37.4275'
#   longitude: '-122.1697'
# directions: Enter Building 1 and take the stairs to Office 200 on Floor 2
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
appointment_url: ''
contact_links:
  - icon: comments
    icon_pack: fab
    name: Send us a message
    link: 'mailto:c562462b.groups.purdue.edu@amer.teams.ms'
  - icon: twitter
    icon_pack: fab
    name: '@Purdue_RCODI'
    link: 'https://twitter.com/Purdue_RCODI'
  - icon: github
    icon_pack: fab
    name: GitHub
    link: 'https://github.com/ironhacks'
  - icon: link
    icon_pack: fas
    name: IronHacks.com
    link: 'https://ironhacks.com'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - py
  - js
  - sh
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/ironhacks/ironhacks-blog'
  content_dir: 'content'
  repo_branch: master
  editable:
    page: false
    post: true
    book: false
    hacks: true
show_related:
  book: false
  page: false
  post: true
  project: false
  publication: false
  event: false
  hack: false
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: false
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: false
    book: false
    project: false
    publication: false
    event: false
    hack: false
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true


# OVERRIDE
i_am_a_sponsor: true
# power_ups:
#   hide_published_with: true
